### PR TITLE
add LGA-28_5.2x3.8mm_Pitch0.5mm package

### PR DESCRIPTION
**Pull request by ChristianHirsch**
Hi @SchrodingersGat: added LGA-28_5.2x3.8mm_Pitch0.5mm package for [Bosch BMF055](https://ae-bst.resource.bosch.com/media/_tech/media/datasheets/BST_BMF055_DS000_01.pdf)
I know that the 3D model is missing..

### CODE REVIEW

**Comment by poeschlr** [comment]
Please add a the 3d model to the footprint. (The information where it might be found if it would exist)
This way if we get a 3d model later on we do not need to change the footprint file.

How did you determine the pad sizes?

**Comment by poeschlr** [comment]
@ChristianHirsch are you still interested in contributing?
The changes i requested are only minor. (should be done within a few minutes.)

**Comment by ChristianHirsch** [comment]
yes, I am @poeschlr. But currently I am busy with other stuff. It's on my list but might take a little bit ;)

**Comment by ChristianHirsch** [comment]
@poeschlr I found time to add the 3d model information. regarding the pad sizes: I used the information from the datasheet and also used the simblee datasheet/footprint (#4) as template. I wanted the pads to be visible when the object is soldered.

**Comment by poeschlr** [comment]
The 3d model path should start with ${KISYS3DMOD}/
This way the user can put their 3d models wherever they want.

**Comment by ChristianHirsch** [comment]
Hi @poeschlr, I changed to path to the 3D model :)

**Comment by poeschlr** [comment]
Thanks for your contribution.

**Pull request merged**
