### PR TITLE
adding LGA-24L_3x3.5_Pitch0.43mm

### PR DESCRIPTION
**Pull request by jeromebeguin**
Footprint for LSM9DS1 from the sensor library

### CODE REVIEW

**Comment by jkriege2** [comment]
Please fix these:
```
checking module: LGA-24L_3x3.5mm_Pitch0.43mm
  Violating Rule 10.7
    All other properties are left to default values. (Move and Place: Free; Auto Place: 0 and 0,  Local
    Clearance Values: 0)
      Attribute solder_mask_margin == 0.15 != 0!

  Violating Rule 6.5
    Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses
    0.12mm line width and provides a reference mark for pin 1. (IPC-7351C).
      Some silkscreen line has a width of 0.1mm, different from 0.12mm (line: {'layer': 'F.SilkS',
      'center': {'y': -1.65, 'x': -1.9}, 'end': {'y': -1.65, 'x': -1.85}, 'width': 0.1}).

  Violating Rule 6.9
    Fabrication layer contains an outline of the part using a 0.1mm line width.
      Some fabrication layer line has a width of 0.2mm, different from 0.1mm.
```

**Comment by jeromebeguin** [comment]
the rule 6.9 is ok, just the point have a thickness of 0.2 to be filled.

**Comment by jkriege2** [comment]
Hi!

I would make the pin1-dot a bit larger:
2017-02-14 18_47_43-footprint editor no active library

Maybe the silkscreen even like this:
2017-02-14 18_50_36-footprint editor no active library
To match the style adopted for BGA here: https://github.com/KiCad/Housings_BGA.pretty/pull/1

Please really make all Silkscreen-lines 0.12mm wide. To fill a circe, just add additional concentric circles until it is filled (all width 0.12mm). The same goes for F.Wab (w=0.1mm of course).

Also to comply with the new version of the KLCs: Please add a label `%R` on F.Fab which will become a sefond REF and should be placed on the same spot as the REFDES on F.SilkS.

Best,
JAN

**Comment by jkriege2** [comment]
nice work!
Thanks,
JAN

**Pull request merged**
