### PR TITLE
add LGA-10-1EP_2.7x4mm_Pitch0.6mm footprint

### PR DESCRIPTION
**Pull request by ChristianHirsch**
with exposed pad based on CCS811 datasheet:
http://ams.com/eng/content/download/951091/2269479/471718

image

Anything to change @poeschlr?

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@ChristianHirsch thanks for your contribution

1. Please add the prefix `AMS_` to the footprint to indicate manufacturer
1. The pin ordering is incorrect on the right-hand-side of the component.

It should be:

| Left | Right |
| ----- | ------- |
| 1 | 10 |
| 2 | 9 |
| 3 | 8 |
| 4 | 7 |
| 5 | 6 |

**Comment by ChristianHirsch** [comment]
Hi @SchrodingersGat You're right, the numbering is wrong.. Fixed everything you mentioned :)

**Comment by SchrodingersGat** [comment]
Thanks. The stencil aperture on the central pad should also be split into 4 parts, to improve the reflow soldering performance. 

screenshot from 2017-07-20 19-09-00

1. Remove the F.Paste layer from all current pads
1. Add 4x new pads with ONLY the F.Paste layer selected

I would suggest dimensions 0.5mm x 1.0mm. However if you can find any further information from AMS that would be good too.

**Comment by SchrodingersGat** [comment]
@ChristianHirsch thanks for your contribution (please ignore my previous comment if you saw it).

**Pull request merged**
