### PR TITLE
Corrected pad numbering sequence, numbering starts from right side clockwise

### PR DESCRIPTION
**Pull request by sandhan26**
https://github.com/KiCad/kicad-library/pull/1796

screenshot from 2017-11-05 00-34-13

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Can you link the datasheet please

**Comment by sandhan26** [comment]
@SchrodingersGat  Refer [Bosch BME280 datasheet](https://ae-bst.resource.bosch.com/media/_tech/media/datasheets/BST-BME280_DS001-11.pdf)

**Comment by SchrodingersGat** [comment]
How weird.

Please rotate such that pin-1 is at top-left corner :)

**Comment by sandhan26** [comment]
@SchrodingersGat top-left corner? But, Pin-1 is at top right corner.

**Comment by poeschlr** [comment]
If you rotate your footprint by 90 degree counter clockwise, pin 1 is on the top left.

I am just confused why bosh would use a mirrored pin numbering scheme to everyone else. Might be a good idea to add a suffix that communicates this fact.

**Comment by sandhan26** [comment]
@poeschlr suffix like this Bosch_LGA-8_2.5x2.5mm_Pitch0.65mm_topRightCW  ?

**Comment by poeschlr** [comment]
nope more like `_mirroredPinLayout`

Pin 1 should still be on the top left. (IPC standard)
screenshot from 2017-11-06 09-00-18

**Comment by evanshultz** [comment]
How about using the term `clockwise` or `counterclockwise`? KLC 3 doesn't provide a list of known/approved conventions for the `[Options]` field, but IMO the word `mirror` has more meanings and is less of an exact description of the pin layout than using CW or CCW.

**Comment by SchrodingersGat** [comment]
I would also lean towards `_Clockwise` being used here

**Comment by SchrodingersGat** [comment]
@sandhan26 please add the `_ClockwisePinNumbering` and I think we are good to merge

**Comment by sandhan26** [comment]
@SchrodingersGat Sorry, have been very busy. But i am on it. I will commit changes soon.

**Comment by sandhan26** [comment]
@SchrodingersGat kindly check, the latest commits. 

One a side note, the corresponding 3d Model also needs to be rotated, right?
https://github.com/KiCad/kicad-library/pull/1796

**Comment by SchrodingersGat** [comment]
Yes the 3D model will need to be rotated. Also, the 3D model reference shows a non-zero offset. Can you please set the 3D model offset to (0 0 0) - the adjustments should be made in the 3D model file to align with the origin of the footprint

**Comment by sandhan26** [comment]
@SchrodingersGat 

In the corresponding 3D model, why do these gaps come?

bme280_in_kicad_gaps

**Comment by SchrodingersGat** [comment]
That looks like a possible issue with the 3D render tool in Kicad, it is putting space between the copper layer and the silkscreen layer... Probably not an issue with the 3D model itsefl

**Pull request merged**
