### PR TITLE
Added HLGA-10

### PR DESCRIPTION
**Pull request by suzizecat**
Hi ! Here is the HLGA-10 used on ST's pressure sensor (at least KiCad/kicad-library#1320 . )
I don't know if this is used anywhere else thought
image

Here is the datasheet [ST LPS25HB Datasheet for HLGA-10](http://www.st.com/content/ccc/resource/technical/document/datasheet/58/d2/33/a4/42/89/42/0b/DM00066332.pdf/files/DM00066332.pdf/jcr:content/translations/en.DM00066332.pdf)

### CODE REVIEW

**Comment by poeschlr** [comment]
Man this datasheet is not really well thought out.
The sketch of the package is missing vital measurments.
Do you know which letter in the table corresponds to the pin measurements? (I would guess L and b. I think these are the only measurements that are not used in the sketch.)

I found this application note that gives more details about the landing pattern
http://www.st.com/content/ccc/resource/technical/document/application_note/a0/f2/a5/e7/58/c8/49/b9/DM00108837.pdf/files/DM00108837.pdf/jcr:content/translations/en.DM00108837.pdf

On page 10 it states that the pads should be 0.1mm larger in y and in x direction compared to the pin itself. (But again, this document does not give pin dimensions anywhere.)
If L and b are the pin measurements than the pads should be 0.55mm long and 0.4mm wide

On page 9 it states that the area below the sensor should be defined as a keepout area (on top copper)

**Comment by suzizecat** [comment]
I downloaded a version of the datasheet with that : 
image
I'm looking up for something online

EDIT : [Here is the datasheet](http://www.st.com/content/ccc/resource/technical/document/datasheet/9a/4c/aa/72/1f/45/4e/24/DM00141379.pdf/files/DM00141379.pdf/jcr:content/translations/en.DM00141379.pdf)

Re-EDIT : 
I didn't intended this footprint to be reserved for the LPS25HB since HLGA-10 seems to be a generic (but unused) packaging. So i don't think that it would be for the best to specify this footprint with a keepout. (Or should i create a "Keepout" version ?)

**Comment by suzizecat** [comment]
I edited the component to meet the application note requirements, but it's not a clean way to do. I had to delete pads from the solder mask and then add some "pads" without copper and only on solder mask. Here what it looks like (i'll need to fix the silkscreen if i keep theses modifications)

It breaks KLC 8.3 but that the only issue.

image

I got these following DS : 
[Application notes for MEMS sensor in HLGA packages - page 4](http://www.st.com/content/ccc/resource/technical/document/technical_note/3a/39/78/0d/81/40/4c/0d/DM00150328.pdf/files/DM00150328.pdf/jcr:content/translations/en.DM00150328.pdf)
[Application notes for LPS25HB - page 10](http://www.st.com/content/ccc/resource/technical/document/application_note/a0/f2/a5/e7/58/c8/49/b9/DM00108837.pdf/files/DM00108837.pdf/jcr:content/translations/en.DM00108837.pdf)
[LPS25HB DS with HLGA dimensions - page 46](http://www.st.com/content/ccc/resource/technical/document/datasheet/9a/4c/aa/72/1f/45/4e/24/DM00141379.pdf/files/DM00141379.pdf/jcr:content/translations/en.DM00141379.pdf)

Could you tell me if i should make multiples footprint (with special naming ?)

**Comment by poeschlr** [comment]
Because your HLGA is specialized to one manufacturers recommendation maybe we should really make one that is generalized and one with the manufacturer prefix plus maybe one with the suffix _MEMS or _keepout with the keepout area defined. (In your symbol for the mems add the one with the keepout area.)

If you want you can include the original footprint without manufacturer prefix as well.

**Comment by suzizecat** [comment]
That should be quite easy, i'll put the one without the the keepout and one another with `_SolderMaskKeepout` suffix. Would it be fine ?

**Comment by poeschlr** [comment]
I would use `manufacturer_footprint-name_keepout`

**Comment by evanshultz** [comment]
@suzizecat Will you be able to make this last change to your PR can be merged?

**Comment by suzizecat** [comment]
@evanshultz @poeschlr just edited.
I increased the silkscreen size to match the component size with extended keepout, so i also increased theses sizes on the "legacy" symbol to match both components

**Comment by poeschlr** [comment]
If you have mask only pads, remove the mask layer from the normal pads.

I think the font on fab would look better with 15% font width (0.075mm)

I would suggest a silk screen like this: (green drawing)
I'm not sure about the pin 1 marker on silk. Maybe the circle would be a good addition but i'm not sure it is needed.
screenshot from 2017-07-18 11-23-51

For the normal HLGA-10 footprint maybe reduce the courtyard size. To match the 0.25mm clearance that is given by the KLC you would need 1.45mm instead of 1.7mm (absolute value for each coordinate.)

**Comment by poeschlr** [comment]
You named the footprint _keepout but you did not add anything to indicate a keepout area.

**Comment by suzizecat** [comment]
> You named the footprint _keepout but you did not add anything to indicate a keepout area.
We may have misunderstood each other...
The keepout here refer to the extended solder mask clearance.

If i change the silkscreen to match your i'm not sure that the 1st pin marking would be fine, but i didn't found (or understood well enough) the IPC specification which KLC refers to... 

I'll update the other stuff as you recommend once i'm sure how should i do the silkscreen.
BTW is there a clean way to create a pin marking dot ? (I just thought about a silkscreen only pad, maybe ?)

**Comment by poeschlr** [comment]
The [pdf (page 17) you posted in one of your other pull requests](https://www.cskl.de/fileadmin/downloads/PCBLIBRARIES/Documentation/What-is-New-in-IPC-7351C_.pdf) contains everything you need to know.
I would go with the qfn type silk screen.
(The chamfer you originally used could be underneath the part which could result in bad solder connections in a reflow process. The enlarged silk screen takes up a lot of unnecessary space.)

**Comment by poeschlr** [comment]
@suzizecat could you take another look at this?

**Comment by suzizecat** [comment]
Sorry, didn't saw your previous message.
I'll take a look at it, RN i'm quite busy with some other things, but i'll try to get it done.

**Comment by poeschlr** [comment]
Posting image here as well for reference.
28310468-dd7017c6-6bac-11e7-8120-8c7db46d1c48

**Comment by SchrodingersGat** [comment]
Hi @suzizecat  thanks for the contribution.

We have now marked this repository as read-only in preparation for the migration over to the new consolidated footprint library repository.

Please resubmit this to the `Package_LGA` library at https://github.com/kicad/kicad-footprints

Thanks very much :)

**Pull request closed without merging**
