### PR TITLE
added Bosch_LGA-8_2.5x2.5mm_Pitch0.65 for Bosch BME680/BME280 sensors

### PR DESCRIPTION
**Pull request by sandhan26**
Hi, kindly review the footprint for [BME680](https://ae-bst.resource.bosch.com/media/_tech/media/datasheets/BST-BME680-DS001-00.pdf) and [BME280](https://ae-bst.resource.bosch.com/media/_tech/media/datasheets/BST-BME280_DS001-11.pdf).

They share the same package LGA-8_2.5x2.5mm_Pitch0.65

screenshot from 2017-10-12 20-36-07

Also, what clearances to add for the pads. Kindly help  in this area, as i am quite new to PCB designing.

### CODE REVIEW

**Comment by sandhan26** [comment]
modified silkscreen outline.

screenshot from 2017-10-13 00-14-39

**Comment by sandhan26** [comment]
couldn't make out the size of the small circular marker pad near pin number 1 from the [datasheet](https://ae-bst.resource.bosch.com/media/_tech/media/datasheets/BST-BME680-DS001-00.pdf)

just took it to be roughly around 0.2mm. Advise needed.

screenshot from 2017-10-13 00-39-44

**Comment by SchrodingersGat** [comment]
That circular marker should not be part of the footprint, it is only an indicator on the package. Please remove it from the copper layer.

Also, please extend the line for pin-1 out to the left, until it almost touches the courtyard. It is important that the shape of this line is fairly different from the other three corners, so that it can be used to easily locate pin-1.

Thanks

**Comment by sandhan26** [comment]
* Removed circular marker
* Extended silkscreen line near pin 1

screenshot from 2017-10-17 21-55-04

**Comment by SchrodingersGat** [comment]
Thanks for the contribution :)

**Comment by sandhan26** [comment]
@SchrodingersGat  help needed.
screenshot from 2017-10-18 15-02-54

**Comment by SchrodingersGat** [comment]
?? You may have to be a bit more specific. What is the problem?

**Comment by sandhan26** [comment]
@SchrodingersGat I need some guidelines/resources on how exactly to prepare a 3d model for use in kicad. 

How do i add the pads in case of SMD coimponents, like this one.

**Comment by SchrodingersGat** [comment]
@Shackmeister @easyw are you able to provide some assistance here? :)

**Pull request merged**
